---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.25.95
vector:
  hosts:
    vector-01:
            ansible_host: 158.160.16.161
lighthouse:
  hosts:
    lighthouse-01:
            ansible_host: 158.160.4.120
